disabled_rules: # rule identifiers to exclude
    # - file_length
    # - function_body_length
    - line_length
    # - missing_docs
    - cyclomatic_complexity
    - block_based_kvo

    - trailing_whitespace
    - identifier_name
    - weak_delegate
    - colon
    - comma
    - control_statement


opt_in_rules:
    - array_init
    - closing_brace
    - closure_end_indentation
    - closure_spacing
    - closure_parameter_position
    - discouraged_object_literal
    - empty_count
    - empty_string
    - explicit_init
    # - force_unwrapping
    - implicit_return
    # Implicit unwrap is avoided in necessary places.
    # - implicitly_unwrapped_optional
    - let_var_whitespace
    - literal_expression_end_indentation
    - operator_usage_whitespace
    - overridden_super_call
    - private_action
    # Used private outlet in required places.
    # - private_outlet  
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test

    - redundant_nil_coalescing

    - required_enum_case
    - trailing_semicolon
    - single_test_class
    - sorted_first_last
    - statement_position
    - file_length
    - switch_case_on_newline
    # - unneeded_parentheses_in_closure_argument
    - vertical_parameter_alignment_on_call
    - yoda_condition
    - cyclomatic_complexity

# Customize behaviour of the existing rules

# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
severity: warning # explicitly

large_tuple: 5

nesting:
    type_level: 2
    statement_level: 5

type_body_length:
    - 500 # warning
    - 600 # error

file_length:
    - 800 # warning
    - 1100 # error

function_parameter_count: 
    - 6 # warning
    - 8 # error

line_length: 
  ignores_comments: true
  ignores_function_declarations: true
  ignores_urls: true
  warning: 200
  error: 600

excluded: # excluded via string array
- id
- URL
- GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)

# **** Steps to integrate Swiftlint **** 

# Swift lint is installed using HomeBrew
    # - brew install swiftlint
# Added below run script in project build phase 
    # *************
    # if which swiftlint >/dev/null; then
    #   swiftlint
    # else
    #   echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
    # fi
    # **************
# .yml file is added using below specified commands
    # cd your_project_directory
    # touch .swiftlint.yml


    #Following rules are enabled in Project, Refer YML confluence page for more reference.
    # - class_delegate_protocol
    # - closing_brace
    # - closure_end_indentation
    # - closure_parameter_position
    # - closure_spacing
    # - colon
    # - comma
    # - control_statement violation
    # - discouraged_object_literal
    # - empty_count
    # - empty_enum_arguments
    # - explicit_init
    # - empty_string
    # - explicit_init
    # - force_cast
    # - force_try
    # - force_unwrapping
    # - for_where
    # - function_body_length
    # - identifier_name
    # - implicit_getter
    # - implicit_return
    # - implicit_unwrapped_optional
    # - large_tuple
    # - leading_whitespace
    # - legacy_constructor
    # - let_var_whitespace
    # - line_length
    # - literal_expression_end_indentation
    # - mark
    # - multiple_closures_with_trailing_closure
    # - opening_brace
    # - operator_whitespace
    # - overridden_super_call
    # - private_action
    # - private_over_fileprivate
    # - private_outlet
    # - redundant_discardable_let
    # - redundant_optional_initialization
    # - return_arrow_whitespace
    # - statement_position
    # - shorthand_operator
    # - switch_case_alignment
    # - switch_case_on_newline
    # - syntactic_sugar
    # - trailing_comma
    # - trailing_semicolon
    # - trailing_whitespace
    # - trailing_newline
    # - type_name
    # - type_body_length
    # - unneeded_break_in_switch
    # - unused_closure_parameter
    # - unused_enumerated
    # - vertical_parameter_alignment
    # - vertical_whitespace
    # - void_return
    # - weak_delegate
