# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgileSrintPlanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Fabric',  '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.4'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseUI'
  pod 'GoogleSignIn'
  # Pods for AgileSrintPlanner

end
